#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import https from 'https';
import { fileURLToPath } from 'url';

// ANSI Escape Codes for CLI Colors
const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const RED = '\x1b[31m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const BLUE = '\x1b[34m';
const MAGENTA = '\x1b[35m';
const CYAN = '\x1b[36m';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Determine if we are in the project root
const PROJECT_ROOT = path.resolve(__dirname, '..');
const LOCAL_SKILLS_DIR = path.join(PROJECT_ROOT, 'skills');

// Default GitHub fallback for wadiolk's official skills
const DEFAULT_GITHUB_OWNER_REPO = 'kokp520/skills';

const ARGS = process.argv.slice(2);
const COMMAND = ARGS[0];

// Default SKILL.md template content
const DEFAULT_SKILL_TEMPLATE = (name) => `---
name: ${name}
description: Describe the role and core features of your new skill ${name}.
---

# ${name}

This skill was automatically generated by Wadiolk. This is a custom skill designed to assist in your automated development workflow.

## Objective
Briefly state the goal of this skill.

## When to use
* When you need to...
* Or when...

## Instructions
Write down the detailed steps and rules you want the Agent to follow.

### 1. Step One
* Detailed description...

### 2. Step Two
* Detailed description...

## Tips
> [!TIP]
> You can use GitHub-style alert blocks (like NOTE, TIP, IMPORTANT, WARNING, CAUTION) to emphasize key points.
`;

// Helper: Ensure directory exists
function ensureDirSync(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

// Helper: Create Symlink
function createSymlink(target, linkPath) {
  try {
    if (fs.existsSync(linkPath)) {
      const lstat = fs.lstatSync(linkPath);
      if (lstat.isSymbolicLink()) {
        fs.unlinkSync(linkPath);
      } else {
        console.log(`${YELLOW}[WARN] Link path ${linkPath} already exists and is not a symbolic link. Skipping...${RESET}`);
        return false;
      }
    }
    
    fs.symlinkSync(target, linkPath, 'dir');
    return true;
  } catch (err) {
    console.error(`${RED}[ERROR] Creating symlink failed: ${linkPath} -> ${target}${RESET}`, err.message);
    return false;
  }
}

// Helper: Recursive copy folder
function copyFolderSync(from, to) {
  ensureDirSync(to);
  fs.readdirSync(from).forEach(element => {
    const fromPath = path.join(from, element);
    const toPath = path.join(to, element);
    if (fs.lstatSync(fromPath).isDirectory()) {
      copyFolderSync(fromPath, toPath);
    } else {
      fs.copyFileSync(fromPath, toPath);
    }
  });
}

// Helper: HTTPS GET request wrapper returning raw text
function downloadRawText(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'Wadiolk-CLI' } }, (res) => {
      if (res.statusCode !== 200) {
        reject(new Error(`Failed to fetch from remote Server. Status Code: ${res.statusCode}`));
        return;
      }
      let data = '';
      res.on('data', (chunk) => { data += chunk; });
      res.on('end', () => { resolve(data); });
    }).on('error', (err) => {
      reject(err);
    });
  });
}

// 1. Create Command
function handleCreate(name) {
  if (!name) {
    console.error(`${RED}[ERROR] Please provide a skill name.${RESET}\nUsage: wadiolk create <skill-name>`);
    process.exit(1);
  }

  const formattedName = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const skillDir = path.join(LOCAL_SKILLS_DIR, formattedName);

  if (fs.existsSync(skillDir)) {
    console.error(`${YELLOW}[WARN] Skill "${formattedName}" already exists at ${skillDir}.${RESET}`);
    process.exit(1);
  }

  ensureDirSync(skillDir);
  const skillMdPath = path.join(skillDir, 'SKILL.md');
  fs.writeFileSync(skillMdPath, DEFAULT_SKILL_TEMPLATE(formattedName), 'utf-8');

  ensureDirSync(path.join(skillDir, 'scripts'));
  ensureDirSync(path.join(skillDir, 'resources'));

  console.log(`${GREEN}[SUCCESS] Created new skill template!${RESET}`);
  console.log(`${BLUE}[INFO] Path:${RESET} ${skillDir}`);
  console.log(`${BLUE}[INFO] File:${RESET} ${skillMdPath}`);
  console.log(`\nNow you can edit ${CYAN}${skillMdPath}${RESET} to write your skill logic.`);
  console.log(`After editing, you can validate it with ${BOLD}make validate${RESET} or install it using ${BOLD}make add name=${formattedName}${RESET}.`);
}

// 2. List Command
function handleList() {
  console.log(`\n${BOLD}Wadiolk Skills List${RESET}`);
  console.log(`=================================`);

  // Local Skills
  console.log(`\n${BLUE}[Local Directory] (${LOCAL_SKILLS_DIR}):${RESET}`);
  if (fs.existsSync(LOCAL_SKILLS_DIR)) {
    const localSkills = fs.readdirSync(LOCAL_SKILLS_DIR).filter(file => {
      const fullPath = path.join(LOCAL_SKILLS_DIR, file);
      return fs.statSync(fullPath).isDirectory() && file !== 'template';
    });

    if (localSkills.length === 0) {
      console.log(`  (No skills found)`);
    } else {
      localSkills.forEach(skill => {
        console.log(`  - ${CYAN}${skill}${RESET}`);
      });
    }
  } else {
    console.log(`  (Directory not yet created)`);
  }
  console.log();
}

// 3. Validate Command
function handleValidate() {
  if (!fs.existsSync(LOCAL_SKILLS_DIR)) {
    console.log(`${YELLOW}[WARN] Local skills directory does not exist.${RESET}`);
    return;
  }

  const localSkills = fs.readdirSync(LOCAL_SKILLS_DIR).filter(file => {
    const fullPath = path.join(LOCAL_SKILLS_DIR, file);
    return fs.statSync(fullPath).isDirectory() && file !== 'template';
  });

  console.log(`${BLUE}[INFO] Validating skills formatting...${RESET}\n`);

  let errorCount = 0;
  let warnCount = 0;

  for (const skill of localSkills) {
    const skillDir = path.join(LOCAL_SKILLS_DIR, skill);
    const skillMdPath = path.join(skillDir, 'SKILL.md');

    if (!fs.existsSync(skillMdPath)) {
      console.log(`  ${RED}[ERROR]${RESET} - ${CYAN}${skill}${RESET}: SKILL.md file not found`);
      errorCount++;
      continue;
    }

    try {
      const content = fs.readFileSync(skillMdPath, 'utf-8');
      const frontmatterMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);

      if (!frontmatterMatch) {
        console.log(`  ${RED}[ERROR]${RESET} - ${CYAN}${skill}${RESET}: SKILL.md is missing Frontmatter (enclosed in ---)`);
        errorCount++;
        continue;
      }

      const frontmatterContent = frontmatterMatch[1];
      const nameMatch = frontmatterContent.match(/^name:\s*(.+)$/m);
      const descMatch = frontmatterContent.match(/^description:\s*(.+)$/m);

      const parsedName = nameMatch ? nameMatch[1].trim() : '';
      const parsedDesc = descMatch ? descMatch[1].trim() : '';

      if (!parsedName) {
        console.log(`  ${RED}[ERROR]${RESET} - ${CYAN}${skill}${RESET}: Missing 'name' field in Frontmatter`);
        errorCount++;
        continue;
      }

      if (!parsedDesc) {
        console.log(`  ${YELLOW}[WARN]${RESET}  - ${CYAN}${skill}${RESET}: Missing 'description' in Frontmatter (highly recommended)`);
        warnCount++;
      } else {
        console.log(`  ${GREEN}[PASS]${RESET}  - ${CYAN}${skill}${RESET} (name: ${parsedName})`);
      }
    } catch (err) {
      console.log(`  ${RED}[ERROR]${RESET} - ${CYAN}${skill}${RESET}: Read or parse failure: ${err.message}`);
      errorCount++;
    }
  }

  console.log(`\n=================================`);
  if (errorCount > 0) {
    console.log(`${RED}[FAIL] Validation failed: Found ${errorCount} severe error(s), ${warnCount} warning(s).${RESET}`);
    process.exit(1);
  } else if (warnCount > 0) {
    console.log(`${YELLOW}[WARN] Validation passed with ${warnCount} warning(s). It is recommended to fix them for optimal performance.${RESET}`);
  } else {
    console.log(`${GREEN}[SUCCESS] Validation passed! All skills comply with standards.${RESET}`);
  }
}

// 4. Add Command (Asynchronous remote and local resolver)
async function handleAdd(inputPath) {
  if (!inputPath) {
    console.error(`${RED}[ERROR] Please specify a skill name or GitHub path to install.${RESET}\nUsage Examples:\n  wadiolk add br-creator (Local fallback)\n  wadiolk add username/repo/skills/some-skill (Remote GitHub)`);
    process.exit(1);
  }

  const targetDir = path.join(process.cwd(), '.gemini', 'skills');

  // Case 1: GitHub URL or Owner/Repo pattern (e.g., adiwu/wadiolk/skills/br-creator)
  const githubPattern = /^(?:github:)?([^/]+)\/([^/]+)(?:\/skills)?\/([^/]+)$/;
  const match = inputPath.match(githubPattern);

  if (match) {
    const owner = match[1];
    const repo = match[2];
    const skillName = match[3];

    const remoteUrl = `https://raw.githubusercontent.com/${owner}/${repo}/main/skills/${skillName}/SKILL.md`;
    const finalTargetDir = path.join(targetDir, skillName);

    console.log(`${BLUE}[INFO] Launching remote installer for "${skillName}"...${RESET}`);
    console.log(`${BLUE}[INFO] URL:${RESET} ${remoteUrl}`);

    try {
      const fileContent = await downloadRawText(remoteUrl);
      
      ensureDirSync(finalTargetDir);
      const skillMdPath = path.join(finalTargetDir, 'SKILL.md');
      fs.writeFileSync(skillMdPath, fileContent, 'utf-8');

      console.log(`${GREEN}[SUCCESS] Remotely downloaded and installed "${skillName}"!${RESET}`);
      console.log(`${BLUE}[INFO] Project Path:${RESET} ${finalTargetDir}`);
    } catch (err) {
      console.error(`${RED}[ERROR] Remote installation failed: ${err.message}${RESET}`);
      console.error(`Please verify that the repository is public and the path "skills/${skillName}/SKILL.md" exists.`);
      process.exit(1);
    }
    return;
  }

  // Case 2: Simple Local Skill fallback (e.g., wadiolk add br-creator)
  const localSourcePath = path.join(LOCAL_SKILLS_DIR, inputPath);

  if (fs.existsSync(localSourcePath) && fs.statSync(localSourcePath).isDirectory()) {
    const finalTargetDir = path.join(targetDir, inputPath);
    if (fs.existsSync(finalTargetDir)) {
      console.log(`${YELLOW}[WARN] Target path already exists at ${finalTargetDir}. Overwriting...${RESET}`);
    }
    try {
      copyFolderSync(localSourcePath, finalTargetDir);
      console.log(`${GREEN}[SUCCESS] Installed "${inputPath}" to current project locally!${RESET}`);
      console.log(`${BLUE}[INFO] Project Path:${RESET} ${finalTargetDir}`);
    } catch (err) {
      console.error(`${RED}[ERROR] Local installation failed: ${err.message}${RESET}`);
    }
  } else {
    // If local copy fails, try to fetch it automatically from your default GitHub Repo
    console.log(`${YELLOW}[INFO] Skill "${inputPath}" not found locally. Searching default remote repository (${DEFAULT_GITHUB_OWNER_REPO})...${RESET}`);
    
    const remoteUrl = `https://raw.githubusercontent.com/${DEFAULT_GITHUB_OWNER_REPO}/main/skills/${inputPath}/SKILL.md`;
    const finalTargetDir = path.join(targetDir, inputPath);

    try {
      const fileContent = await downloadRawText(remoteUrl);
      ensureDirSync(finalTargetDir);
      const skillMdPath = path.join(finalTargetDir, 'SKILL.md');
      fs.writeFileSync(skillMdPath, fileContent, 'utf-8');

      console.log(`${GREEN}[SUCCESS] Remotely downloaded and installed "${inputPath}" from ${DEFAULT_GITHUB_OWNER_REPO}!${RESET}`);
      console.log(`${BLUE}[INFO] Project Path:${RESET} ${finalTargetDir}`);
    } catch (err) {
      console.error(`${RED}[ERROR] Skill "${inputPath}" could not be resolved locally or remotely.${RESET}`);
      console.error(`Attempted remote path: ${remoteUrl}`);
      process.exit(1);
    }
  }
}

// 5. Help
function handleHelp() {
  console.log(`
${BOLD}${MAGENTA}Wadiolk - Custom Skills Developer Kit${RESET}

${BOLD}Usage:${RESET}
  wadiolk <command> [args]

${BOLD}Commands:${RESET}
  ${GREEN}create <name>${RESET}   Create a new custom skill template in local directory
  ${GREEN}list${RESET}            Display the list of local custom skills
  ${GREEN}validate${RESET}        Validate the format of local skills (Frontmatter checks)
  ${GREEN}add <path>${RESET}      Install specified skill into current project's .gemini/skills/ directory
                  Supports local name: "br-creator"
                  Supports remote GitHub: "username/repo/skills/skill-name"
  ${GREEN}help${RESET}            Display this help message
`);
}

// Route dispatcher
(async () => {
  switch (COMMAND) {
    case 'create':
      handleCreate(ARGS[1]);
      break;
    case 'list':
      handleList();
      break;
    case 'validate':
      handleValidate();
      break;
    case 'add':
      await handleAdd(ARGS[1]);
      break;
    case 'help':
    default:
      handleHelp();
      break;
  }
})();
