#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import os from 'os';
import { fileURLToPath } from 'url';

// ANSI Escape Codes for CLI Colors
const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const RED = '\x1b[31m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const BLUE = '\x1b[34m';
const MAGENTA = '\x1b[35m';
const CYAN = '\x1b[36m';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Determine if we are in the project root
const PROJECT_ROOT = path.resolve(__dirname, '..');
const LOCAL_SKILLS_DIR = path.join(PROJECT_ROOT, 'skills');

// Target system directories
const AGENT_SKILLS_DIR = path.join(os.homedir(), '.agent', 'skills');
const GEMINI_SKILLS_DIR = path.join(os.homedir(), '.gemini', 'skills');

const ARGS = process.argv.slice(2);
const COMMAND = ARGS[0];

// Default SKILL.md template content
const DEFAULT_SKILL_TEMPLATE = (name) => `---
name: ${name}
description: Describe the role and core features of your new skill ${name}.
---

# ${name}

This skill was automatically generated by Wadiolk. This is a custom skill designed to assist in your automated development workflow.

## Objective
Briefly state the goal of this skill.

## When to use
* When you need to...
* Or when...

## Instructions
Write down the detailed steps and rules you want the Agent to follow.

### 1. Step One
* Detailed description...

### 2. Step Two
* Detailed description...

## Tips
> [!TIP]
> You can use GitHub-style alert blocks (like NOTE, TIP, IMPORTANT, WARNING, CAUTION) to emphasize key points.
`;

// Helper: Ensure directory exists
function ensureDirSync(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

// Helper: Create Symlink
function createSymlink(target, linkPath) {
  try {
    if (fs.existsSync(linkPath)) {
      const lstat = fs.lstatSync(linkPath);
      if (lstat.isSymbolicLink()) {
        fs.unlinkSync(linkPath);
      } else {
        console.log(`${YELLOW}[WARN] Link path ${linkPath} already exists and is not a symbolic link. Skipping...${RESET}`);
        return false;
      }
    }
    
    fs.symlinkSync(target, linkPath, 'dir');
    return true;
  } catch (err) {
    console.error(`${RED}[ERROR] Creating symlink failed: ${linkPath} -> ${target}${RESET}`, err.message);
    return false;
  }
}

// Helper: Recursive copy folder
function copyFolderSync(from, to) {
  ensureDirSync(to);
  fs.readdirSync(from).forEach(element => {
    const fromPath = path.join(from, element);
    const toPath = path.join(to, element);
    if (fs.lstatSync(fromPath).isDirectory()) {
      copyFolderSync(fromPath, toPath);
    } else {
      fs.copyFileSync(fromPath, toPath);
    }
  });
}

// 1. Create Command
function handleCreate(name) {
  if (!name) {
    console.error(`${RED}[ERROR] Please provide a skill name.${RESET}\nUsage: wadiolk create <skill-name>`);
    process.exit(1);
  }

  const formattedName = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const skillDir = path.join(LOCAL_SKILLS_DIR, formattedName);

  if (fs.existsSync(skillDir)) {
    console.error(`${YELLOW}[WARN] Skill "${formattedName}" already exists at ${skillDir}.${RESET}`);
    process.exit(1);
  }

  ensureDirSync(skillDir);
  const skillMdPath = path.join(skillDir, 'SKILL.md');
  fs.writeFileSync(skillMdPath, DEFAULT_SKILL_TEMPLATE(formattedName), 'utf-8');

  ensureDirSync(path.join(skillDir, 'scripts'));
  ensureDirSync(path.join(skillDir, 'resources'));

  console.log(`${GREEN}[SUCCESS] Created new skill template!${RESET}`);
  console.log(`${BLUE}[INFO] Path:${RESET} ${skillDir}`);
  console.log(`${BLUE}[INFO] File:${RESET} ${skillMdPath}`);
  console.log(`\nNow you can edit ${CYAN}${skillMdPath}${RESET} to write your skill logic.`);
  console.log(`After editing, run ${BOLD}make link${RESET} to publish it to the Agent.`);
}

// 2. Link Command
function handleLink() {
  if (!fs.existsSync(LOCAL_SKILLS_DIR)) {
    console.log(`${YELLOW}[WARN] Local skills directory does not exist. Creating...${RESET}`);
    ensureDirSync(LOCAL_SKILLS_DIR);
  }

  const localSkills = fs.readdirSync(LOCAL_SKILLS_DIR).filter(file => {
    const fullPath = path.join(LOCAL_SKILLS_DIR, file);
    return fs.statSync(fullPath).isDirectory() && file !== 'template';
  });

  if (localSkills.length === 0) {
    console.log(`${YELLOW}[INFO] No custom skills found. Run 'make new name=<name>' to create one first.${RESET}`);
    return;
  }

  ensureDirSync(AGENT_SKILLS_DIR);
  ensureDirSync(GEMINI_SKILLS_DIR);

  console.log(`${BLUE}[INFO] Linking skills to Agent system directories...${RESET}`);
  
  let successCount = 0;
  for (const skill of localSkills) {
    const sourcePath = path.join(LOCAL_SKILLS_DIR, skill);
    
    const agentLinkPath = path.join(AGENT_SKILLS_DIR, skill);
    const geminiLinkPath = path.join(GEMINI_SKILLS_DIR, skill);

    const s1 = createSymlink(sourcePath, agentLinkPath);
    const s2 = createSymlink(sourcePath, geminiLinkPath);

    if (s1 || s2) {
      console.log(`  [OK] Linked ${CYAN}${skill}${RESET}`);
      successCount++;
    }
  }

  console.log(`\n${GREEN}[SUCCESS] Linked ${successCount} skills to the system.${RESET}`);
  console.log(`Now you can use them directly in your Agent conversations.`);
}

// 3. Unlink Command
function handleUnlink() {
  if (!fs.existsSync(LOCAL_SKILLS_DIR)) {
    console.log(`${YELLOW}[INFO] Local skills directory does not exist.${RESET}`);
    return;
  }

  const localSkills = fs.readdirSync(LOCAL_SKILLS_DIR).filter(file => {
    const fullPath = path.join(LOCAL_SKILLS_DIR, file);
    return fs.statSync(fullPath).isDirectory();
  });

  console.log(`${YELLOW}[INFO] Removing skill symbolic links from the system...${RESET}`);

  let removedCount = 0;
  const unlinkSymlink = (linkPath) => {
    if (fs.existsSync(linkPath)) {
      try {
        const lstat = fs.lstatSync(linkPath);
        if (lstat.isSymbolicLink()) {
          fs.unlinkSync(linkPath);
          return true;
        }
      } catch (err) {
        console.error(`${RED}[ERROR] Failed to remove symlink: ${linkPath}${RESET}`, err.message);
      }
    }
    return false;
  };

  for (const skill of localSkills) {
    const agentLinkPath = path.join(AGENT_SKILLS_DIR, skill);
    const geminiLinkPath = path.join(GEMINI_SKILLS_DIR, skill);

    const u1 = unlinkSymlink(agentLinkPath);
    const u2 = unlinkSymlink(geminiLinkPath);

    if (u1 || u2) {
      console.log(`  [OK] Removed ${CYAN}${skill}${RESET}`);
      removedCount++;
    }
  }

  console.log(`\n${GREEN}[SUCCESS] Unloaded ${removedCount} skills.${RESET}`);
}

// 4. List Command
function handleList() {
  console.log(`\n${BOLD}Wadiolk Skills List${RESET}`);
  console.log(`=================================`);

  // Local Skills
  console.log(`\n${BLUE}[Local Directory] (${LOCAL_SKILLS_DIR}):${RESET}`);
  if (fs.existsSync(LOCAL_SKILLS_DIR)) {
    const localSkills = fs.readdirSync(LOCAL_SKILLS_DIR).filter(file => {
      const fullPath = path.join(LOCAL_SKILLS_DIR, file);
      return fs.statSync(fullPath).isDirectory() && file !== 'template';
    });

    if (localSkills.length === 0) {
      console.log(`  (No skills found)`);
    } else {
      localSkills.forEach(skill => {
        console.log(`  - ${CYAN}${skill}${RESET}`);
      });
    }
  } else {
    console.log(`  (Directory not yet created)`);
  }

  // Active Symlinks
  console.log(`\n${BLUE}[Active Symlinks] (~/.agent/skills):${RESET}`);
  if (fs.existsSync(AGENT_SKILLS_DIR)) {
    const activeSkills = fs.readdirSync(AGENT_SKILLS_DIR).filter(file => {
      const fullPath = path.join(AGENT_SKILLS_DIR, file);
      try {
        return fs.lstatSync(fullPath).isSymbolicLink();
      } catch {
        return false;
      }
    });

    if (activeSkills.length === 0) {
      console.log(`  (No custom symbolic links found)`);
    } else {
      activeSkills.forEach(skill => {
        const target = fs.readlinkSync(path.join(AGENT_SKILLS_DIR, skill));
        console.log(`  - ${GREEN}${skill}${RESET} -> ${target}`);
      });
    }
  } else {
    console.log(`  (System directory not yet created)`);
  }
  console.log();
}

// 5. Validate Command
function handleValidate() {
  if (!fs.existsSync(LOCAL_SKILLS_DIR)) {
    console.log(`${YELLOW}[WARN] Local skills directory does not exist.${RESET}`);
    return;
  }

  const localSkills = fs.readdirSync(LOCAL_SKILLS_DIR).filter(file => {
    const fullPath = path.join(LOCAL_SKILLS_DIR, file);
    return fs.statSync(fullPath).isDirectory() && file !== 'template';
  });

  console.log(`${BLUE}[INFO] Validating skills formatting...${RESET}\n`);

  let errorCount = 0;
  let warnCount = 0;

  for (const skill of localSkills) {
    const skillDir = path.join(LOCAL_SKILLS_DIR, skill);
    const skillMdPath = path.join(skillDir, 'SKILL.md');

    if (!fs.existsSync(skillMdPath)) {
      console.log(`  ${RED}[ERROR]${RESET} - ${CYAN}${skill}${RESET}: SKILL.md file not found`);
      errorCount++;
      continue;
    }

    try {
      const content = fs.readFileSync(skillMdPath, 'utf-8');
      const frontmatterMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);

      if (!frontmatterMatch) {
        console.log(`  ${RED}[ERROR]${RESET} - ${CYAN}${skill}${RESET}: SKILL.md is missing Frontmatter (enclosed in ---)`);
        errorCount++;
        continue;
      }

      const frontmatterContent = frontmatterMatch[1];
      const nameMatch = frontmatterContent.match(/^name:\s*(.+)$/m);
      const descMatch = frontmatterContent.match(/^description:\s*(.+)$/m);

      const parsedName = nameMatch ? nameMatch[1].trim() : '';
      const parsedDesc = descMatch ? descMatch[1].trim() : '';

      if (!parsedName) {
        console.log(`  ${RED}[ERROR]${RESET} - ${CYAN}${skill}${RESET}: Missing 'name' field in Frontmatter`);
        errorCount++;
        continue;
      }

      if (!parsedDesc) {
        console.log(`  ${YELLOW}[WARN]${RESET}  - ${CYAN}${skill}${RESET}: Missing 'description' in Frontmatter (highly recommended)`);
        warnCount++;
      } else {
        console.log(`  ${GREEN}[PASS]${RESET}  - ${CYAN}${skill}${RESET} (name: ${parsedName})`);
      }
    } catch (err) {
      console.log(`  ${RED}[ERROR]${RESET} - ${CYAN}${skill}${RESET}: Read or parse failure: ${err.message}`);
      errorCount++;
    }
  }

  console.log(`\n=================================`);
  if (errorCount > 0) {
    console.log(`${RED}[FAIL] Validation failed: Found ${errorCount} severe error(s), ${warnCount} warning(s).${RESET}`);
    process.exit(1);
  } else if (warnCount > 0) {
    console.log(`${YELLOW}[WARN] Validation passed with ${warnCount} warning(s). It is recommended to fix them for optimal performance.${RESET}`);
  } else {
    console.log(`${GREEN}[SUCCESS] Validation passed! All skills comply with standards.${RESET}`);
  }
}

// 6. Add Command
function handleAdd(name) {
  if (!name) {
    console.error(`${RED}[ERROR] Please specify the skill name to install.${RESET}\nUsage: wadiolk add <skill-name>`);
    process.exit(1);
  }

  const sourcePath = path.join(LOCAL_SKILLS_DIR, name);
  if (!fs.existsSync(sourcePath) || !fs.statSync(sourcePath).isDirectory()) {
    console.error(`${RED}[ERROR] Skill "${name}" not found in Wadiolk library.${RESET}\nYou can run "wadiolk list" to view available skills.`);
    process.exit(1);
  }

  const targetDir = path.join(process.cwd(), '.gemini', 'skills', name);
  
  if (fs.existsSync(targetDir)) {
    console.log(`${YELLOW}[INFO] Target path already exists at ${targetDir}. Overwriting...${RESET}`);
  }

  try {
    copyFolderSync(sourcePath, targetDir);
    console.log(`${GREEN}[SUCCESS] Installed "${name}" to current project!${RESET}`);
    console.log(`${BLUE}[INFO] Project Path:${RESET} ${targetDir}`);
    console.log(`Now commit this project to Git so other collaborators' Agents can use this skill.`);
  } catch (err) {
    console.error(`${RED}[ERROR] Installation failed: ${err.message}${RESET}`);
  }
}

// 7. Help
function handleHelp() {
  console.log(`
${BOLD}${MAGENTA}Wadiolk - Custom Skills Developer Kit${RESET}

${BOLD}Usage:${RESET}
  wadiolk <command> [args]

${BOLD}Commands:${RESET}
  ${GREEN}create <name>${RESET}   Create a new custom skill template in local directory
  ${GREEN}link${RESET}            Symlink all local skills to the Agent's system directory
  ${GREEN}unlink${RESET}          Remove all Wadiolk symlinks from the system directory
  ${GREEN}list${RESET}            Display the list of local and linked custom skills
  ${GREEN}validate${RESET}        Validate the format of local skills (Frontmatter checks)
  ${GREEN}add <name>${RESET}      Copy specified skill into current project's .gemini/skills/ directory
  ${GREEN}help${RESET}            Display this help message

${BOLD}System Paths:${RESET}
  - Agent Skills:  ${CYAN}${AGENT_SKILLS_DIR}${RESET}
  - Gemini Skills: ${CYAN}${GEMINI_SKILLS_DIR}${RESET}
`);
}

// Route dispatcher
switch (COMMAND) {
  case 'create':
    handleCreate(ARGS[1]);
    break;
  case 'link':
    handleLink();
    break;
  case 'unlink':
    handleUnlink();
    break;
  case 'list':
    handleList();
    break;
  case 'validate':
    handleValidate();
    break;
  case 'add':
    handleAdd(ARGS[1]);
    break;
  case 'help':
  default:
    handleHelp();
    break;
}
